[package]
name = "fix-skin"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.38.0", features = ["full"] }
clap = {version = "4.5.9", features = [ "derive" ]}
image = "0.25.1"
anyhow = "1.0.86"
rayon = "1.10.0"
